#ifndef MY_ROLODEX_ADDRESS_HPP
#define MY_ROLODEX_ADDRESS_HPP


/**
 * DO NOT EDIT THIS FILE
 */


//
#include <string>


//
namespace CPSC131::MyRolodex
{
	//
	class Address
	{
		public:
			
			std::string line1;
			std::string line2;
			std::string city;
			std::string state;
			int zip;
			std::string country;
			
			std::string toString()
			{
				std::string s;
				
				s += this->line1 + "\n";
				if ( !this->line2.empty() ) {
					s += this->line2 + "\n";
				}
				s += this->city + ", " + this->state + ", " + std::to_string(this->zip) + "\n";
				s += this->country + "\n";
				
				return s;
			}
			
			bool operator==(const Address& other)
			{
				if
				(
					this->line1 == other.line1
					&& this->line2 == other.line2
					&& this->city == other.city
					&& this->state == other.state
					&& this->zip == other.zip
					&& this->country == other.country
				)
				{
					return true;
				}
				
				return false;
			}
			
			bool operator!=(const Address& other)
			{
				return !(*this == other);
			}
	};
}


#endif
